basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_detail, name='basket_detail'),
    path('add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('remove/<int:product_id>/', views.basket_remove, name='basket_remove'),
    path('checkout/', views.checkout, name='checkout'),
    path('place-order/', views.placeorder, name='placeorder'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basket/', include('basket.urls', namespace='basket')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),

    path('all_products/', views.all_products, name='all_products'),
    path('all_products_by_price_min/', views.all_products_by_price_min, name='all_products_by_price_min'),
    path('all_products_by_price_max/', views.all_products_by_price_max, name='all_products_by_price_max'),

    path('search/', views.search, name='search'),

    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# клас для фільтрації виводу товарів
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    color = models.CharField(max_length=40, blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.jpeg', null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    # кастомізуємо наш вивід продуктів
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    # Перенаправляє нас URL з назвою товару
    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title


class Order(models.Model):
    first_name = models.CharField(max_length=150, null=False)
    last_name = models.CharField(max_length=150, null=False)
    email = models.CharField(max_length=150, null=False)
    phone = models.CharField(max_length=150, null=False)
    address = models.CharField(max_length=150, null=False)
    city = models.CharField(max_length=150, null=False)
    zipcode = models.CharField(max_length=150, null=False)

    total_price = models.FloatField(null=False)

    order_status = (
        ('Pending', 'Pending'),
        ('Out for Shipping', 'Out for Shipping'),
        ('Completed', 'Completed'),
    )
    status = models.CharField(max_length=150, choices=order_status, default='Pending')
    tracking_no = models.CharField(max_length=150, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id} - {self.tracking_no}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.FloatField(null=False)
    quantity = models.IntegerField(null=False)

    def __str__(self):
        return f"{self.order.id} - {self.order.tracking_no}"

basket/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

basket/views.py
import random

from .basket import Basket
from .forms import CartAddProductForm
from store.models import Product, Order, OrderItem

from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST


@require_POST
def basket_add(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        basket.add(product=product,
                   quantity=cd['quantity'],
                   update_quantity=cd['update'])
    return redirect('basket:basket_detail')


def basket_remove(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    basket.delete(product)
    return redirect('basket:basket_detail')


def basket_detail(request):
    basket = Basket(request)
    for item in basket:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})

    return render(request, 'store/basket/basket_detail.html', {'basket': basket})


def checkout(request):
    return render(request, 'store/basket/checkout.html')


@require_POST
def placeorder(request):
    neworder = Order()
    neworder.first_name = request.POST.get('first_name')
    neworder.last_name = request.POST.get('last_name')
    neworder.email = request.POST.get('email')
    neworder.phone = request.POST.get('phone')
    neworder.address = request.POST.get('address')
    neworder.city = request.POST.get('city')
    neworder.zipcode = request.POST.get('zipcode')

    basket = Basket(request)
    neworder.total_price = basket.get_total_price()

    track_no = 'razer_' + str(random.randint(1111, 9999))
    while Order.objects.filter(tracking_no=track_no) is None:
        track_no = 'razer_' + str(random.randint(1111, 9999))
    neworder.tracking_no = track_no

    neworder.save()

    for item in basket:
        OrderItem.objects.create(
            order=neworder,
            product=item['product'],
            price=item['product'].price,
            quantity=item['quantity'],
        )

    basket.clear()

    messages.success(
        request,
        f'{neworder.first_name}, your order "{track_no}" '
        f'has been placed successfully, wait for the operator to call you.')

    return render(request, 'store/home.html')

store/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_GET

from basket.forms import CartAddProductForm
from .models import Category, Product


def home(request):
    return render(request, 'store/home.html')


def all_products(request):
    products = Product.products.order_by('?')[:]
    return render(request, 'store/all_products.html', {'products': products})


#  this was made just for the test
@login_required(login_url='/users/login/')
def all_products_by_price_min(request):
    products = Product.products.order_by('price')
    return render(request, 'store/all_products.html', {'products': products})


def all_products_by_price_max(request):
    products = Product.products.order_by('-price')
    return render(request, 'store/all_products.html', {'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.products.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    # в product передається конкретний товар і вже по цьому в single.html виводиться інфа
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    basket_product_form = CartAddProductForm()
    return render(request, 'store/products/single.html',
                  {'product': product,
                   'basket_product_form': basket_product_form,
                   })


def search(request):
    query = request.GET.get('query')

    if query:
        price = Product.objects.filter(price__icontains=query)
        category = Category.objects.filter(name__icontains=query)
        title = Product.objects.filter(title__icontains=query)
        if price:
            return render(request, 'store/search.html', {'products': price, 'query': query})
        elif category:
            for item in category:
                all_filtered = Product.objects.filter(category=item)
                return render(request, 'store/search.html', {'products': all_filtered, 'query': query})
        elif title:
            return render(request, 'store/search.html', {'products': title, 'query': query})
        else:
            return render(request, 'store/search.html', {'query': query})
    else:
        messages.success(request, "Please enter some value, like... 'mice', 'razer', etc.")
        return render(request, 'store/search.html')

templates/store/basket/basket_detail.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}Basket Summary{% endblock %}
{% block content %}

    <main class="pt-5">

        <div>
            <a class="btn btn-outline-success" href="{% url 'store:all_products' %}">To the Razer's Store</a>
            {% if basket|length > 0 %}
                <a href="{% url 'basket:checkout' %}" class="btn btn-warning">Checkout</a>
            {% else %}
                <h4 class="text-center" style="color:green;">The basket is empty!</h4>
            {% endif %}
        </div>
        <hr>

        <div class="container">

            <h1 class="h5">Razer's basket</h1>

            {% for item in basket %}
                {% with product=item.product %}

                    <div data-index="{{ product.id }}" class="row mb-4 border product-item shadow">

                        <div class="col-md-2 mt-4 col-lg-2 order-md-first bg-light">
                            <img class="img-fluid mx-auto d-block image" alt="Responsive image"
                                 src="{{ product.image.url }}">
                        </div>


                        <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">


                            <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
                                <h1 class="h5 pt-2">{{ product.title }}</h1>
                            </a>

                            <div class="border-info">


                                {# форма для зв'язку #}
                                <form action="{% url 'basket:basket_add' product.id %}" method="post">


                                    {# Ціна за 1 штуку #}
                                    <div class="col border-bottom">
                                        <div class="row p-3">
                                            <div class="col-6">Price:</div>
                                            <div class="col-6 text-end"><span
                                                    class="h6 fw-bold">UAH: {{ product.price }}</span>
                                            </div>
                                        </div>
                                    </div>


                                    {# Загальна ціна за КОНКРЕТНИЙ товар #}
                                    <div class="col border-bottom">
                                        <div class="row p-3">
                                            <div class="col-6">Total price for item:</div>
                                            <div class="col-6 text-end"><span
                                                    class="h6 fw-bold">UAH: {{ item.total_price }}</span>
                                            </div>
                                        </div>
                                    </div>


                                    {# апдейт та делейт #}
                                    <div class="col mb-3">
                                        <div class="row p-3">
                                            <div class="col-6" style="margin-top: 5px">
                                                Quantity: {{ item.update_quantity_form.quantity }}</div>
                                            <div class="col-6 text-end"><span
                                                    class="h6 fw-bold">{{ item.update_quantity_form.update }}
                                        <input class="btn btn-outline-success" type="submit" value="Update"></span>
                                                <a class="btn btn-outline-danger"
                                                   href="{% url 'basket:basket_remove' product.id %}">Delete</a>
                                            </div>
                                        </div>
                                    </div>


                                    {% csrf_token %}
                                </form>


                            </div>
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}

            {# загальна вартість всіх товарів в корзині #}
            <div class="col-12 text-end border-bottom">
                <div class="h5 fw-bold">Total UAH:
                    <div id="subtotal" class="d-inline-flex" style="color:green;">{{ basket.get_total_price }}</div>
                </div>
            </div>

            {# завершення покупки #}
            <div class="col-12 text-end mt-3">
                {% if basket|length > 0 %}
                    <a href="{% url 'basket:checkout' %}" class="btn btn-warning">Checkout</a>
                {% endif %}
            </div>

        </div>
    </main>

{% endblock %}

templates/store/basket/checkout.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}Checkout{% endblock %}
{% block content %}

    <div class="py-3" xmlns="http://www.w3.org/1999/html">
        <div class="container">
            <a class="btn btn-outline-secondary" href="{% url 'store:home' %}">Home</a>
            <a class="btn btn-outline-success" href="{% url 'basket:basket_detail' %}">Back to Basket</a>
        </div>
    </div>
    <div class="container">
        <form action="{% url 'basket:placeorder' %}" method="post">
            {% csrf_token %}

            <div class="row">
                <div class="col-md-6">
                    <div class="card shadow">
                        <div class="card-body">
                            <h5>Customer Details:</h5>
                            <hr>

                            {# Інформація про покупця #}
                            <div class="row check_out_form">

                                <div class="col-md-6">
                                        <label for="">First name:</label>
                                        <input aria-label="" required class="form-control" type="text" name="first_name"
                                               placeholder="Enter first name">
                                </div>

                                <div class="col-md-6">
                                    <label for="">Last name:</label>
                                    <input aria-label="" required class="form-control" type="text" name="last_name"
                                           placeholder="Enter Last name">
                                </div>

                                <div class="col-md-6 mt-1">
                                    <label for="">Email:</label>
                                    <input aria-label="" required class="form-control" type="text" name="email"
                                           placeholder="Enter Email">
                                </div>

                                <div class="col-md-6 mt-1">
                                    <label for="">Phone number:</label>
                                    <input aria-label="" required class="form-control" type="text" name="phone"
                                           placeholder="Enter phone number">
                                </div>

                                <div class="col-md-12 mt-1">
                                    <label for="">Address</label>
                                    <textarea aria-label="" required class="form-control" type="text" name="address"
                                              placeholder="Enter Address"></textarea>
                                </div>

                                <div class="col-md-6 mt-1">
                                    <label for="">City</label>
                                    <input aria-label="" required class="form-control" type="text" name="city"
                                           placeholder="Enter City">
                                </div>

                                <div class="col-md-6 mt-1">
                                    <label for="">Zip code</label>
                                    <input aria-label="" required class="form-control" type="text" name="zipcode"
                                           placeholder="Enter Zip Code">
                                </div>

                            </div>

                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="card shadow">
                        <div class="card-body">
                            <h5>Order Summary</h5>
                            <hr>
                            {% if basket %}
                                <table class="table table-striped table-bordereds">
                                    <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th>Quantity</th>
                                        <th>Price</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for item in basket %}
                                        <tr>
                                            <td>
                                                <img class="me-2 image" height="65px" width="65px"
                                                     alt="Responsive image"
                                                     src="{{ item.product.image.url }}">
                                            </td>
                                            <td>{{ item.product.title }}</td>
                                            <td>{{ item.quantity }}</td>
                                            <td>{{ item.total_price }}</td>

                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                                <h5 class="total">Total Price:
                                    <span class="float-end total"> UAH: {{ basket.get_total_price }}</span>
                                </h5>
                                <div class="mt-3">
                                    <button type="submit" class="btn btn-success w-100">Place Order</button>
                                </div>

                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>



{% endblock %}

templates/store/basket/end_order.html
{% extends 'store/base.html' %}

{% block content %}

    <hr>
    <p class='text-center h2' style="color: #14c821">Thank's for your order!</p>
{% endblock content %}