basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_detail, name='basket_detail'),
    path('add/<int:product_id>/', views.basket_add, name='basket_add'),
    path('remove/<int:product_id>/', views.basket_remove, name='basket_remove'),
    path('checkout/', views.checkout, name='checkout'),
    path('place-order/', views.placeorder, name='placeorder'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contact_page, name='contact_page'),
    ]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basket/', include('basket.urls', namespace='basket')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),

    path('all_products/', views.all_products, name='all_products'),
    path('all_products_by_price_min/', views.all_products_by_price_min, name='all_products_by_price_min'),
    path('all_products_by_price_max/', views.all_products_by_price_max, name='all_products_by_price_max'),

    path('search/', views.search, name='search'),

    path('<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    # Включити URL авторизацію за замовчуванням
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
]

store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# клас для фільтрації виводу товарів
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    color = models.CharField(max_length=40, blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.jpeg', null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    # кастомізуємо наш вивід продуктів
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    # Перенаправляє нас URL з назвою товару
    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title


class Order(models.Model):
    first_name = models.CharField(max_length=150, null=False)
    last_name = models.CharField(max_length=150, null=False)
    email = models.CharField(max_length=150, null=False)
    phone = models.CharField(max_length=150, null=False)
    address = models.CharField(max_length=150, null=False)
    city = models.CharField(max_length=150, null=False)
    zipcode = models.CharField(max_length=150, null=False)

    total_price = models.FloatField(null=False)

    order_status = (
        ('Pending', 'Pending'),
        ('Out for Shipping', 'Out for Shipping'),
        ('Completed', 'Completed'),
    )
    status = models.CharField(max_length=150, choices=order_status, default='Pending')
    tracking_no = models.CharField(max_length=150, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id} - {self.tracking_no}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.FloatField(null=False)
    quantity = models.IntegerField(null=False)

    def __str__(self):
        return f"{self.order.id} - {self.order.tracking_no}"

store/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_GET

from basket.forms import CartAddProductForm
from .models import Category, Product


def home(request):
    return render(request, 'store/home.html')


def all_products(request):
    products = Product.products.order_by('?')[:]
    return render(request, 'store/all_products.html', {'products': products})


#  this was made just for the test
@login_required(login_url='/users/login/')
def all_products_by_price_min(request):
    products = Product.products.order_by('price')
    return render(request, 'store/all_products.html', {'products': products})


def all_products_by_price_max(request):
    products = Product.products.order_by('-price')
    return render(request, 'store/all_products.html', {'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.products.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    # в product передається конкретний товар і вже по цьому в single.html виводиться інфа
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    basket_product_form = CartAddProductForm()
    return render(request, 'store/products/single.html',
                  {'product': product,
                   'basket_product_form': basket_product_form,
                   })


def search(request):
    query = request.GET.get('query')

    if query:
        price = Product.objects.filter(price__icontains=query)
        category = Category.objects.filter(name__icontains=query)
        title = Product.objects.filter(title__icontains=query)
        if price:
            return render(request, 'store/search.html', {'products': price, 'query': query})
        elif category:
            for item in category:
                all_filtered = Product.objects.filter(category=item)
                return render(request, 'store/search.html', {'products': all_filtered, 'query': query})
        elif title:
            return render(request, 'store/search.html', {'products': title, 'query': query})
        else:
            return render(request, 'store/search.html', {'query': query})
    else:
        messages.success(request, "Please enter some value, like... 'mice', 'razer', etc.")
        return render(request, 'store/search.html')

templates/store/all_products.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
    <div class="album py-4 bg-light">
        <div class="container">

            {# вивід товарів: ВСІХ МІНІМАЛЬНИХ МАКСИМАЛЬНИХ #}
            <div class="row row-cols-2 row-cols-sm-2 row-cols-md-4 g-3 mb-2">
                <a class="btn btn-outline-primary" style="padding: 10px; transition: 1000ms; margin: 10px auto"
                   href="{% url 'store:all_products' %}">All</a>
                <a class="btn btn-outline-success" style="padding: 10px; transition: 1000ms; margin: 10px auto"
                   href="{% url 'store:all_products_by_price_min' %}">Lowest price</a>
                <a class="btn btn-outline-danger" style="padding: 10px; transition: 1000ms; margin: 10px auto"
                   href="{% url 'store:all_products_by_price_max' %}">Highest price</a>
            </div>

            <div class="row row-cols-2 row-cols-sm-3 row-cols-md-3 g-3">

                {% for product in products %}

                <div class="col">
                    <div class="card shadow-sm p-2">

                        {% if product.image %}
                        <a href="{{ product.get_absolute_url }}"><img class="img-fluid"
                                                                      src="{{ product.image.url }}"
                                                                      alt="No image found for {{ product.title }}"></a>
                        {% else %}
                        <img class="img-fluid" src="/media/images/default.jpeg" alt="None">
                        {% endif %}

                        <div class="card-body">
                            <hr>
                            <h5>
                                <a class="cart-text" style="text-decoration: none; color: inherit"

                                   href="{{ product.get_absolute_url }}"><strong>{{ product.title }}</strong>
                                </a>
                            </h5>
                            <a class="btn btn-outline-success" href="{{ product.get_absolute_url }}">View</a>
                            <h4 style="display: inline-block;float: right">
                                <small style="color: green">UAH: {{ product.price|floatformat:2 }}</small>
                            </h4>
                        </div>
                    </div>
                </div>

                {% endfor %}

            </div>

        </div>
    </div>


</main>

{% endblock %}

templates/store/base.html
{% load static %}
<!doctype html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}RazerStore{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href=" {% static 'css/base.css' %}">
</head>

<body>
<header>

    <nav class="navbar navbar-expand-md navbar-light bg-dark border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'store:home' %}"><img src="/media/images/text_razer_navbar.png"
                                                                       style="width: 230px; height: 55px" alt=""></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item active">
                        <a class="nav-link all_p" aria-current="page" href="{% url 'store:all_products' %}"
                           style="color: #14c821; margin-left: 20px; font-size: 20px">All products</a>
                    </li>

                    {# випидаюче вікно #}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false"
                           style="color: #14c821; margin-left: 15px; font-size: 20px">
                            Categories
                        </a>

                        {# елементи випадаючого вікна #}
                        <ul class="dropdown-menu bg-dark" aria-labelledby="navbarCollapse">
                            {% for c in categories %}
                            <li>
                                <a class="dropdown-item h4"
                                   style="color: #14c821; transition: 1500ms; font-size: 20px"
                                   href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                            </li>
                            {% endfor %}

                        </ul>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" aria-current="page" href="{% url 'contact:contact_page' %}"
                           style="color: #14c821; margin-left: 20px; font-size: 20px">Contact</a>
                    </li>

                </ul>


                {# search form #}
                <form class="d-flex" action="{% url 'store:search' %}" method="get" role="search"
                      style="margin-right: 40px">
                    <input class="form-control me-2" type="text" name="query" placeholder="Go on!" aria-label="Search">
                    <button class="btn btn-outline-success" style="color: #14c821" type="submit">Search</button>
                </form>


                {# login and log out #}
                <div class="form-inline my-2 my-lg-0" style="margin-right: 20px">

                    {# якщо юзер увійшов #}
                    {% if user.is_authenticated %}
                    <span class="navbar-text"
                          style="color: #14c821; margin-right: 20px">Hello, {{ user.username|upper }} !</span>
                    <a href="{% url 'users:logout' %}" style="color: white"
                       class="btn btn-danger button_log">Log out</a>
                    {% else %}
                    <a type="button" role='button' href="{% url 'users:login' %}"
                       style="color: #14c821; margin: 10px"
                       class="btn btn-outline-success button_log"> Login</a>
                    <a href="{% url 'users:register' %}" style="color: white; margin: 10px"
                       class="btn btn-success button_log">Sign
                        Up</a>
                    {% endif %}
                </div>


                {# basket #}
                <a type="button" role='button' href="{% url 'basket:basket_detail' %}"
                   class="btn btn-outline-secondary" style="color: #14c821">
                    {% with total_qty=basket|length %}
                    <div id="basket-qty" class="d-inline-flex">
                        {% if total_qty > 0 %}
                        {{ total_qty }}
                        {% else %}
                        0
                        {% endif %}
                    </div>
                    {% endwith %}

                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-cart3" viewBox="0 0 16 16">
                        <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"></path>
                    </svg>
                    Basket
                </a>
            </div>
        </div>
    </nav>
</header>

<div class="wrapper" style="display: flex; flex-direction: column; min-height: 91vh">

    <div class="container" style="flex: 1">
        <br>
        {% block content %}

        {% endblock content %}
    </div>

    {# telegram bot #}
    <script src="https://apps.elfsight.com/p/platform.js" defer></script>
    <div class="elfsight-app-80f963d1-a76f-45f1-9059-5652c2483d4a"></div>


    <footer class="bg-dark text-center text-lg-start" style="margin-top: 20px">
        <div class="container p-4">
            <div class="row">
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0" style="color: lawngreen">
                    <h5 class="text-uppercase">RazerStore</h5>

                    <p style="color: white">
                        Experience true quality and excellence!
                    </p>
                </div>

                <div class="col-lg-6 col-md-12 mb-4 mb-md-0" style="color: lawngreen">
                    <h5 class="text-uppercase">Магазин Razer</h5>

                    <p style="color: white">
                        Відчуй справжню якість та досконалість!
                    </p>
                </div>

            </div>
        </div>

        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); color: lawngreen">
            © 2023 Copyright:
            <a class="text" style="color: white;" href="/">RazerStore.com</a>
        </div>
    </footer>

</div>
</body>

templates/store/home.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}


{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-success m-2" id="msg" role="alert">{{ message }}</div>
{% endfor %}
{% endif %}

<section class="py-4 text-center container">

    <img class="img-fluid" style="margin-bottom: 50px" src="/media/images/for_gamers.jpeg" alt="">
</section>


{# про нас #}
<div class="row">
    <div class="col-md-5">
        <div class="card-text">
            <h4 class="text-center" style="color: green">About us</h4>
            <ul class="list text-small">
                <hr>
                <li class="text-muted">Location:</li>
                <p>Ukraine, Vinnitsia, 12, Yushchenka str. 8</p>
                <li class="text-muted">Phone number:</li>
                <p style="color: green">+38 (093) 11-22-469</p>
                <li class="text-muted">Email:</li>
                <p>RazerStore@razer.com</p>
                <li class="text-muted">Owner</li>
                <p style="color: green">Khimich Vladyslav</p>
                <hr>
                <p class="text-center"><img src="/media/images/for%20by.jpeg" alt=""></p>
            </ul>
        </div>
    </div>

    {# гугл карта #}
    <div class="col-md-7">
        <h4 class="text-center" style="color: green">Location of our Razer's Store</h4>

        <div class="card">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2605.993762557111!2d28.442933015958136!3d49.219645383155715!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x472d5b8805fbb0dd%3A0x50477f4d66a14fdf!2z0YPQuy4g0JDQutCw0LTQtdC80LjQutCwINCu0YnQtdC90LrQviwg0JLQuNC90L3QuNGG0LAsINCS0LjQvdC90LjRhtC60LDRjyDQvtCx0LvQsNGB0YLRjCwgMjEwMDA!5e0!3m2!1sru!2sua!4v1675850537059!5m2!1sru!2sua"
                    width=100% height="450" style="border:0;" allowfullscreen="" loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
</div>


{% endblock content %}

templates/store/search.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
    <div class="album py-4 bg-light">
        <div class="container">

            {% if query|length < 1 %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger m-2" id="msg" role="alert">{{ message }}</div>
            {% endfor %}
            {% endif %}
            <hr>
            {% else %}
            <h3>Your are searching by the name:</h3>

            <h2 style="color: green">"{{ query }}"</h2>
            <hr>
            {% endif %}
            {% if products %}
            <div class="row row-cols-2 row-cols-sm-3 row-cols-md-3 g-3">

                {% for product in products %}

                <div class="col">
                    <div class="card shadow-sm">

                        {% if product.image %}
                        <a href="{{ product.get_absolute_url }}"><img class="img-fluid"
                                                                      src="{{ product.image.url }}"
                                                                      alt="No image found for {{ product.title }}"></a>
                        {% else %}
                        <img class="img-fluid" src="/media/images/default.jpeg" alt="None">
                        {% endif %}

                        <div class="card-body">
                            <hr>
                            <h5>
                                <a class="cart-text" style="text-decoration: none; color: inherit"

                                   href="{{ product.get_absolute_url }}"><strong>{{ product.title }}</strong>
                                </a>
                            </h5>
                            <a class="btn btn-outline-success"
                               href="{{ product.get_absolute_url }}">View</a>
                            <h4 style="display: inline-block;float: right">
                                <small style="color: green">UAH: {{ product.price|floatformat:2 }}</small>
                            </h4>
                        </div>
                    </div>
                </div>

                {% endfor %}
                {% else %}
                <p class="h4" style="color: red">Razer products with the name "{{ query }}" is not available!</p>
                {% endif %}

            </div>
        </div>
    </div>


</main>

{% endblock %}